// <auto-generated />
using System;
using Content.Server.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Content.Server.Database.Migrations.Sqlite
{
    [DbContext(typeof(SqliteServerDbContext))]
    [Migration("20260105000000_AddRankIdToProfile")]
    partial class AddRankIdToProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This migration adds RankId column to Profile table
            // The full model is defined in SqliteServerDbContextModelSnapshot
            
            #pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");
            #pragma warning restore 612, 618
        }
    }
}
