// <auto-generated />
using System;
using System.Text.Json;
using Content.Server.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Content.Server.Database.Migrations.Sqlite
{
    [DbContext(typeof(SqliteServerDbContext))]
    [Migration("20260105010000_AddMaxRankPayGrade")]
    partial class AddMaxRankPayGrade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This migration adds MaxRankPayGrade column to Preference table
            // The full model is defined in SqliteServerDbContextModelSnapshot
            
            #pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");
            #pragma warning restore 612, 618
        }
    }
}
