using System.Numerics;
using Content.Client.UserInterface.Controls;
using Prometheus;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class LobbyCharacterPreviewPanel : Control
{
    [Dependency] private readonly IEntityManager _entManager = default!;

    public Button CharacterSetupButton => CharacterSetup;

    private EntityUid? _previewDummy;

    public LobbyCharacterPreviewPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void SetLoaded(bool value)
    {
        Loaded.Visible = value;
        Unloaded.Visible = !value;
    }

    public void SetSummaryText(string value)
    {
        Summary.Text = value;
    }

    // Frontier: show bank balance on character selection.
    public void SetBankBalanceText(string value)
    {
        BankBalance.Text = value;
    }
    // End Frontier

    // Company Display
    public void SetCompanyText(string value)
    {
        if (string.IsNullOrEmpty(value))
        {
            Company.SetMessage(string.Empty);
            return;
        }

        Company.SetMessage(FormattedMessage.FromMarkupPermissive(value));
    }
    // End Company Display

    // Rank Display
    public void SetRankText(string? rankId, IPrototypeManager prototypeManager)
    {
        if (string.IsNullOrEmpty(rankId) || !prototypeManager.TryIndex<Content.Shared._Mako.Ranks.RankPrototype>(rankId, out var rankProto))
        {
            CharacterRank.SetMessage(string.Empty);
            return;
        }

        // Get color based on pay grade
        var color = rankProto.PayGrade switch
        {
            >= 1 and <= 3 => "#C0C0C0",    // E1-E3: off-grey
            >= 4 and <= 9 => "#FFFFFF",    // E4-E9: white
            >= 15 and <= 18 => "#FFD700",  // O1-O4: gold
            >= 19 => "#B8860B",            // O5+: dark gold
            _ => "#FFFFFF"                  // Warrant and others: white
        };

        var message = FormattedMessage.FromMarkupPermissive($"[color={color}]{rankProto.Name}[/color]");
        CharacterRank.SetMessage(message);
    }
    // End Rank Display

    // MonoCoins Display
    public void SetMonoCoinsText(string value)
    {
        MonoCoins.Text = value;
    }
    // End MonoCoins Display

    public void SetSprite(EntityUid uid)
    {
        if (_previewDummy != null)
        {
            _entManager.DeleteEntity(_previewDummy);
        }

        _previewDummy = uid;

        ViewBox.DisposeAllChildren();
        var spriteView = new SpriteView
        {
            OverrideDirection = Direction.South,
            Scale = new Vector2(4f, 4f),
            MaxSize = new Vector2(112, 112),
            Stretch = SpriteView.StretchMode.Fill,
        };
        spriteView.SetEntity(uid);
        ViewBox.AddChild(spriteView);
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        _entManager.DeleteEntity(_previewDummy);
        _previewDummy = null;
    }
}
